import Head from 'next/head';
import Image from 'next/image';
import Header from "../components/Header";


export default function Home() {
  return (
    <>
      <Head>
        <title>MatPizz🍕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <Header />
        <main>conteudo</main>
      </div>
    </>
  )
}
