import Head from 'next/head';
import Header from "../components/Header";
import { slogan, address, phone, whattsapp} from "../data/matpizza.json";

export default function Home() {
  return (
    <>
      <Head>
        <title>MatPizz🍕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <Header />
        <main>
          <h2 className='slogan'>{slogan}</h2>

          <div className='info'>
            <p><strong>🏠 Endereço: </strong>{address}</p>
            <p><strong>☎️ Telefone: </strong>{phone}</p>
            <p><strong>📱 whattsapp: </strong>{whattsapp}</p>
          </div>
        </main>
      </div>
    </>
  )
}
